/*
 * Ticket Vendor API
 * An API for listing events and reserving/ordering tickets for an event
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package de.workshops.ticketeer.ticketvendor.model;

import com.google.gson.JsonElement;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

/**
 * Gets or Sets EventCategory
 */
@JsonAdapter(EventCategory.Adapter.class)
public enum EventCategory {

  MUSIC("music"),

  CIRCUS("circus"),

  THEATER("theater"),

  OPERA("opera"),

  SPORT("sport"),

  OTHER("other");

  private String value;

  EventCategory(String value) {
    this.value = value;
  }

  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  public static EventCategory fromValue(String value) {
    for (EventCategory b : EventCategory.values()) {
      if (b.value.equals(value)) {
        return b;
      }
    }
    throw new IllegalArgumentException("Unexpected value '" + value + "'");
  }

  public static class Adapter extends TypeAdapter<EventCategory> {

    @Override
    public void write(final JsonWriter jsonWriter, final EventCategory enumeration)
        throws IOException {
      jsonWriter.value(enumeration.getValue());
    }

    @Override
    public EventCategory read(final JsonReader jsonReader) throws IOException {
      String value = jsonReader.nextString();
      return EventCategory.fromValue(value);
    }
  }

  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
    String value = jsonElement.getAsString();
    EventCategory.fromValue(value);
  }
}

