/*
 * Ticket Vendor API
 * An API for listing events and reserving/ordering tickets for an event
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package de.workshops.ticketeer.ticketvendor.model;

import com.google.gson.Gson;
import com.google.gson.JsonArray;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.TypeAdapter;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.annotations.SerializedName;
import com.google.gson.reflect.TypeToken;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.Set;
import java.util.UUID;
import lombok.Setter;

/**
 * Event
 */
@Setter
public class Event {

  public static final String SERIALIZED_NAME_ID = "id";
  @SerializedName(SERIALIZED_NAME_ID)
  private UUID id;

  public static final String SERIALIZED_NAME_NAME = "name";
  @SerializedName(SERIALIZED_NAME_NAME)
  private String name;

  public static final String SERIALIZED_NAME_ARTISTS = "artists";
  @SerializedName(SERIALIZED_NAME_ARTISTS)
  private List<Artist> artists = new ArrayList<>();

  public static final String SERIALIZED_NAME_CATEGORY = "category";
  @SerializedName(SERIALIZED_NAME_CATEGORY)
  private EventCategory category;

  public static final String SERIALIZED_NAME_DATE = "date";
  @SerializedName(SERIALIZED_NAME_DATE)
  private OffsetDateTime date;

  public static final String SERIALIZED_NAME_LOCATION = "location";
  @SerializedName(SERIALIZED_NAME_LOCATION)
  private Location location;

  public static final String SERIALIZED_NAME_TICKETS = "tickets";
  @SerializedName(SERIALIZED_NAME_TICKETS)
  private List<Ticket> tickets = new ArrayList<>();

  public static final String SERIALIZED_NAME_STATUS = "status";
  @SerializedName(SERIALIZED_NAME_STATUS)
  private EventStatus status;

  public Event() {
  }

  public Event id(UUID id) {
    this.id = id;
    return this;
  }

  /**
   * Get id
   *
   * @return id
   */
  public UUID getId() {
    return id;
  }


  public Event name(String name) {
    this.name = name;
    return this;
  }

  /**
   * Get name
   *
   * @return name
   */
  public String getName() {
    return name;
  }


  public Event artists(List<Artist> artists) {
    this.artists = artists;
    return this;
  }

  public Event addArtistsItem(Artist artistsItem) {
    if (this.artists == null) {
      this.artists = new ArrayList<>();
    }
    this.artists.add(artistsItem);
    return this;
  }

  /**
   * Get artists
   *
   * @return artists
   */
  public List<Artist> getArtists() {
    return artists;
  }


  public Event category(EventCategory category) {
    this.category = category;
    return this;
  }

  /**
   * Get category
   *
   * @return category
   */
  public EventCategory getCategory() {
    return category;
  }


  public Event date(OffsetDateTime date) {
    this.date = date;
    return this;
  }

  /**
   * Get date
   *
   * @return date
   */
  public OffsetDateTime getDate() {
    return date;
  }


  public Event location(Location location) {
    this.location = location;
    return this;
  }

  /**
   * Get location
   *
   * @return location
   */
  public Location getLocation() {
    return location;
  }


  public Event tickets(List<Ticket> tickets) {
    this.tickets = tickets;
    return this;
  }

  public Event addTicketsItem(Ticket ticketsItem) {
    if (this.tickets == null) {
      this.tickets = new ArrayList<>();
    }
    this.tickets.add(ticketsItem);
    return this;
  }

  /**
   * Get tickets
   *
   * @return tickets
   */
  public List<Ticket> getTickets() {
    return tickets;
  }


  public Event status(EventStatus status) {
    this.status = status;
    return this;
  }

  /**
   * Get status
   *
   * @return status
   */
  public EventStatus getStatus() {
    return status;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Event event = (Event) o;
    return Objects.equals(this.id, event.id) &&
        Objects.equals(this.name, event.name) &&
        Objects.equals(this.artists, event.artists) &&
        Objects.equals(this.category, event.category) &&
        Objects.equals(this.date, event.date) &&
        Objects.equals(this.location, event.location) &&
        Objects.equals(this.tickets, event.tickets) &&
        Objects.equals(this.status, event.status);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, name, artists, category, date, location, tickets, status);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Event {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    artists: ").append(toIndentedString(artists)).append("\n");
    sb.append("    category: ").append(toIndentedString(category)).append("\n");
    sb.append("    date: ").append(toIndentedString(date)).append("\n");
    sb.append("    location: ").append(toIndentedString(location)).append("\n");
    sb.append("    tickets: ").append(toIndentedString(tickets)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces (except the first
   * line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("id");
    openapiFields.add("name");
    openapiFields.add("artists");
    openapiFields.add("category");
    openapiFields.add("date");
    openapiFields.add("location");
    openapiFields.add("tickets");
    openapiFields.add("status");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
    openapiRequiredFields.add("id");
    openapiRequiredFields.add("name");
    openapiRequiredFields.add("date");
    openapiRequiredFields.add("location");
    openapiRequiredFields.add("tickets");
    openapiRequiredFields.add("status");
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to Event
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
    if (jsonElement == null) {
      if (!Event.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
        throw new IllegalArgumentException(
            String.format("The required field(s) %s in Event is not found in the empty JSON string",
                Event.openapiRequiredFields.toString()));
      }
    }

    Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
    // check to see if the JSON string contains additional fields
    for (Map.Entry<String, JsonElement> entry : entries) {
      if (!Event.openapiFields.contains(entry.getKey())) {
        throw new IllegalArgumentException(String.format(
            "The field `%s` in the JSON string is not defined in the `Event` properties. JSON: %s",
            entry.getKey(), jsonElement.toString()));
      }
    }

    // check to make sure all required properties/fields are present in the JSON string
    for (String requiredField : Event.openapiRequiredFields) {
      if (jsonElement.getAsJsonObject().get(requiredField) == null) {
        throw new IllegalArgumentException(
            String.format("The required field `%s` is not found in the JSON string: %s",
                requiredField, jsonElement.toString()));
      }
    }
    JsonObject jsonObj = jsonElement.getAsJsonObject();
    if (!jsonObj.get("id").isJsonPrimitive()) {
      throw new IllegalArgumentException(String.format(
          "Expected the field `id` to be a primitive type in the JSON string but got `%s`",
          jsonObj.get("id").toString()));
    }
    if (!jsonObj.get("name").isJsonPrimitive()) {
      throw new IllegalArgumentException(String.format(
          "Expected the field `name` to be a primitive type in the JSON string but got `%s`",
          jsonObj.get("name").toString()));
    }
    if (jsonObj.get("artists") != null && !jsonObj.get("artists").isJsonNull()) {
      JsonArray jsonArrayartists = jsonObj.getAsJsonArray("artists");
      if (jsonArrayartists != null) {
        // ensure the json data is an array
        if (!jsonObj.get("artists").isJsonArray()) {
          throw new IllegalArgumentException(String.format(
              "Expected the field `artists` to be an array in the JSON string but got `%s`",
              jsonObj.get("artists").toString()));
        }

        // validate the optional field `artists` (array)
        for (int i = 0; i < jsonArrayartists.size(); i++) {
          Artist.validateJsonElement(jsonArrayartists.get(i));
        }
        ;
      }
    }
    // validate the optional field `category`
    if (jsonObj.get("category") != null && !jsonObj.get("category").isJsonNull()) {
      EventCategory.validateJsonElement(jsonObj.get("category"));
    }
    // validate the required field `location`
    Location.validateJsonElement(jsonObj.get("location"));
    // ensure the json data is an array
    if (!jsonObj.get("tickets").isJsonArray()) {
      throw new IllegalArgumentException(String.format(
          "Expected the field `tickets` to be an array in the JSON string but got `%s`",
          jsonObj.get("tickets").toString()));
    }

    JsonArray jsonArraytickets = jsonObj.getAsJsonArray("tickets");
    // validate the required field `tickets` (array)
    for (int i = 0; i < jsonArraytickets.size(); i++) {
      Ticket.validateJsonElement(jsonArraytickets.get(i));
    }
    ;
    // validate the required field `status`
    EventStatus.validateJsonElement(jsonObj.get("status"));
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {

    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
      if (!Event.class.isAssignableFrom(type.getRawType())) {
        return null; // this class only serializes 'Event' and its subtypes
      }
      final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
      final TypeAdapter<Event> thisAdapter
          = gson.getDelegateAdapter(this, TypeToken.get(Event.class));

      return (TypeAdapter<T>) new TypeAdapter<Event>() {
        @Override
        public void write(JsonWriter out, Event value) throws IOException {
          JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
          elementAdapter.write(out, obj);
        }

        @Override
        public Event read(JsonReader in) throws IOException {
          JsonElement jsonElement = elementAdapter.read(in);
          validateJsonElement(jsonElement);
          return thisAdapter.fromJsonTree(jsonElement);
        }

      }.nullSafe();
    }
  }
}

