/*
 * Ticket Vendor API
 * An API for listing events and reserving/ordering tickets for an event
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package de.workshops.ticketeer.ticketvendor.model;

import com.google.gson.JsonElement;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

/**
 * Gets or Sets EventStatus
 */
@JsonAdapter(EventStatus.Adapter.class)
public enum EventStatus {

  ANNOUNCED("announced"),

  OPEN("open"),

  SOLD_OUT("sold out");

  private String value;

  EventStatus(String value) {
    this.value = value;
  }

  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  public static EventStatus fromValue(String value) {
    for (EventStatus b : EventStatus.values()) {
      if (b.value.equals(value)) {
        return b;
      }
    }
    throw new IllegalArgumentException("Unexpected value '" + value + "'");
  }

  public static class Adapter extends TypeAdapter<EventStatus> {

    @Override
    public void write(final JsonWriter jsonWriter, final EventStatus enumeration)
        throws IOException {
      jsonWriter.value(enumeration.getValue());
    }

    @Override
    public EventStatus read(final JsonReader jsonReader) throws IOException {
      String value = jsonReader.nextString();
      return EventStatus.fromValue(value);
    }
  }

  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
    String value = jsonElement.getAsString();
    EventStatus.fromValue(value);
  }
}

