/*
 * Ticket Vendor API
 * An API for listing events and reserving/ordering tickets for an event
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package de.workshops.ticketeer.ticketvendor.model;

import com.google.gson.Gson;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.TypeAdapter;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.annotations.SerializedName;
import com.google.gson.reflect.TypeToken;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.HashSet;
import java.util.Map;
import java.util.Objects;
import java.util.Set;
import lombok.Setter;

/**
 * Ticket
 */
@Setter
public class Ticket {

  public static final String SERIALIZED_NAME_TOTAL_NUMBER = "totalNumber";
  @SerializedName(SERIALIZED_NAME_TOTAL_NUMBER)
  private Integer totalNumber;

  public static final String SERIALIZED_NAME_RESERVED = "reserved";
  @SerializedName(SERIALIZED_NAME_RESERVED)
  private Integer reserved;

  public static final String SERIALIZED_NAME_ORDERED = "ordered";
  @SerializedName(SERIALIZED_NAME_ORDERED)
  private Integer ordered;

  public static final String SERIALIZED_NAME_CATEGORY = "category";
  @SerializedName(SERIALIZED_NAME_CATEGORY)
  private String category;

  public static final String SERIALIZED_NAME_PRICE = "price";
  @SerializedName(SERIALIZED_NAME_PRICE)
  private Price price;

  public Ticket() {
  }

  public Ticket totalNumber(Integer totalNumber) {
    this.totalNumber = totalNumber;
    return this;
  }

  /**
   * Total number of event tickets for a certain category.
   *
   * @return totalNumber
   */
  public Integer getTotalNumber() {
    return totalNumber;
  }


  public Ticket reserved(Integer reserved) {
    this.reserved = reserved;
    return this;
  }

  /**
   * Number of reserved event tickets for a certain category.
   *
   * @return reserved
   */
  public Integer getReserved() {
    return reserved;
  }


  public Ticket ordered(Integer ordered) {
    this.ordered = ordered;
    return this;
  }

  /**
   * Number of ordered event tickets for a certain category.
   *
   * @return ordered
   */
  public Integer getOrdered() {
    return ordered;
  }


  public Ticket category(String category) {
    this.category = category;
    return this;
  }

  /**
   * Get category
   *
   * @return category
   */
  public String getCategory() {
    return category;
  }


  public Ticket price(Price price) {
    this.price = price;
    return this;
  }

  /**
   * Ticket price in this category
   *
   * @return price
   */
  public Price getPrice() {
    return price;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Ticket ticket = (Ticket) o;
    return Objects.equals(this.totalNumber, ticket.totalNumber) &&
        Objects.equals(this.reserved, ticket.reserved) &&
        Objects.equals(this.ordered, ticket.ordered) &&
        Objects.equals(this.category, ticket.category) &&
        Objects.equals(this.price, ticket.price);
  }

  @Override
  public int hashCode() {
    return Objects.hash(totalNumber, reserved, ordered, category, price);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Ticket {\n");
    sb.append("    totalNumber: ").append(toIndentedString(totalNumber)).append("\n");
    sb.append("    reserved: ").append(toIndentedString(reserved)).append("\n");
    sb.append("    ordered: ").append(toIndentedString(ordered)).append("\n");
    sb.append("    category: ").append(toIndentedString(category)).append("\n");
    sb.append("    price: ").append(toIndentedString(price)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces (except the first
   * line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("totalNumber");
    openapiFields.add("reserved");
    openapiFields.add("ordered");
    openapiFields.add("category");
    openapiFields.add("price");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
    openapiRequiredFields.add("totalNumber");
    openapiRequiredFields.add("price");
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to Ticket
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
    if (jsonElement == null) {
      if (!Ticket.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
        throw new IllegalArgumentException(String.format(
            "The required field(s) %s in Ticket is not found in the empty JSON string",
            Ticket.openapiRequiredFields.toString()));
      }
    }

    Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
    // check to see if the JSON string contains additional fields
    for (Map.Entry<String, JsonElement> entry : entries) {
      if (!Ticket.openapiFields.contains(entry.getKey())) {
        throw new IllegalArgumentException(String.format(
            "The field `%s` in the JSON string is not defined in the `Ticket` properties. JSON: %s",
            entry.getKey(), jsonElement.toString()));
      }
    }

    // check to make sure all required properties/fields are present in the JSON string
    for (String requiredField : Ticket.openapiRequiredFields) {
      if (jsonElement.getAsJsonObject().get(requiredField) == null) {
        throw new IllegalArgumentException(
            String.format("The required field `%s` is not found in the JSON string: %s",
                requiredField, jsonElement.toString()));
      }
    }
    JsonObject jsonObj = jsonElement.getAsJsonObject();
    if ((jsonObj.get("category") != null && !jsonObj.get("category").isJsonNull()) && !jsonObj.get(
        "category").isJsonPrimitive()) {
      throw new IllegalArgumentException(String.format(
          "Expected the field `category` to be a primitive type in the JSON string but got `%s`",
          jsonObj.get("category").toString()));
    }
    // validate the required field `price`
    Price.validateJsonElement(jsonObj.get("price"));
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {

    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
      if (!Ticket.class.isAssignableFrom(type.getRawType())) {
        return null; // this class only serializes 'Ticket' and its subtypes
      }
      final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
      final TypeAdapter<Ticket> thisAdapter
          = gson.getDelegateAdapter(this, TypeToken.get(Ticket.class));

      return (TypeAdapter<T>) new TypeAdapter<Ticket>() {
        @Override
        public void write(JsonWriter out, Ticket value) throws IOException {
          JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
          elementAdapter.write(out, obj);
        }

        @Override
        public Ticket read(JsonReader in) throws IOException {
          JsonElement jsonElement = elementAdapter.read(in);
          validateJsonElement(jsonElement);
          return thisAdapter.fromJsonTree(jsonElement);
        }

      }.nullSafe();
    }
  }
}

