/*
 * Ticket Vendor API
 * An API for listing events and reserving/ordering tickets for an event
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package de.workshops.ticketeer.ticketvendor.model;

import com.google.gson.Gson;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.TypeAdapter;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.annotations.SerializedName;
import com.google.gson.reflect.TypeToken;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.time.OffsetDateTime;
import java.util.HashSet;
import java.util.Map;
import java.util.Objects;
import java.util.Set;
import java.util.UUID;
import org.openapitools.client.JSON;

/**
 * TicketReservationResponse
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-12-23T15:26:40.830974+01:00[Europe/Berlin]", comments = "Generator version: 7.7.0")
public class TicketReservationResponse {

  public static final String SERIALIZED_NAME_ID = "id";
  @SerializedName(SERIALIZED_NAME_ID)
  private UUID id;

  public static final String SERIALIZED_NAME_VALID_UNTIL = "validUntil";
  @SerializedName(SERIALIZED_NAME_VALID_UNTIL)
  private OffsetDateTime validUntil;

  public static final String SERIALIZED_NAME_NUMBER = "number";
  @SerializedName(SERIALIZED_NAME_NUMBER)
  private Integer number;

  public static final String SERIALIZED_NAME_TICKET_PRICE = "ticketPrice";
  @SerializedName(SERIALIZED_NAME_TICKET_PRICE)
  private Price ticketPrice;

  public static final String SERIALIZED_NAME_TOTAL_PRICE = "totalPrice";
  @SerializedName(SERIALIZED_NAME_TOTAL_PRICE)
  private Price totalPrice;

  public TicketReservationResponse() {
  }

  public TicketReservationResponse id(UUID id) {
    this.id = id;
    return this;
  }

  /**
   * reservation ID
   *
   * @return id
   */
  @javax.annotation.Nonnull
  public UUID getId() {
    return id;
  }

  public void setId(UUID id) {
    this.id = id;
  }


  public TicketReservationResponse validUntil(OffsetDateTime validUntil) {
    this.validUntil = validUntil;
    return this;
  }

  /**
   * Get validUntil
   *
   * @return validUntil
   */
  @javax.annotation.Nonnull
  public OffsetDateTime getValidUntil() {
    return validUntil;
  }

  public void setValidUntil(OffsetDateTime validUntil) {
    this.validUntil = validUntil;
  }


  public TicketReservationResponse number(Integer number) {
    this.number = number;
    return this;
  }

  /**
   * Get number minimum: 1
   *
   * @return number
   */
  @javax.annotation.Nonnull
  public Integer getNumber() {
    return number;
  }

  public void setNumber(Integer number) {
    this.number = number;
  }


  public TicketReservationResponse ticketPrice(Price ticketPrice) {
    this.ticketPrice = ticketPrice;
    return this;
  }

  /**
   * Get ticketPrice
   *
   * @return ticketPrice
   */
  @javax.annotation.Nonnull
  public Price getTicketPrice() {
    return ticketPrice;
  }

  public void setTicketPrice(Price ticketPrice) {
    this.ticketPrice = ticketPrice;
  }


  public TicketReservationResponse totalPrice(Price totalPrice) {
    this.totalPrice = totalPrice;
    return this;
  }

  /**
   * Get totalPrice
   *
   * @return totalPrice
   */
  @javax.annotation.Nonnull
  public Price getTotalPrice() {
    return totalPrice;
  }

  public void setTotalPrice(Price totalPrice) {
    this.totalPrice = totalPrice;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TicketReservationResponse ticketReservationResponse = (TicketReservationResponse) o;
    return Objects.equals(this.id, ticketReservationResponse.id) &&
        Objects.equals(this.validUntil, ticketReservationResponse.validUntil) &&
        Objects.equals(this.number, ticketReservationResponse.number) &&
        Objects.equals(this.ticketPrice, ticketReservationResponse.ticketPrice) &&
        Objects.equals(this.totalPrice, ticketReservationResponse.totalPrice);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, validUntil, number, ticketPrice, totalPrice);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class TicketReservationResponse {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    validUntil: ").append(toIndentedString(validUntil)).append("\n");
    sb.append("    number: ").append(toIndentedString(number)).append("\n");
    sb.append("    ticketPrice: ").append(toIndentedString(ticketPrice)).append("\n");
    sb.append("    totalPrice: ").append(toIndentedString(totalPrice)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces (except the first
   * line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("id");
    openapiFields.add("validUntil");
    openapiFields.add("number");
    openapiFields.add("ticketPrice");
    openapiFields.add("totalPrice");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
    openapiRequiredFields.add("id");
    openapiRequiredFields.add("validUntil");
    openapiRequiredFields.add("number");
    openapiRequiredFields.add("ticketPrice");
    openapiRequiredFields.add("totalPrice");
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to TicketReservationResponse
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
    if (jsonElement == null) {
      if (!TicketReservationResponse.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
        throw new IllegalArgumentException(String.format(
            "The required field(s) %s in TicketReservationResponse is not found in the empty JSON string",
            TicketReservationResponse.openapiRequiredFields.toString()));
      }
    }

    Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
    // check to see if the JSON string contains additional fields
    for (Map.Entry<String, JsonElement> entry : entries) {
      if (!TicketReservationResponse.openapiFields.contains(entry.getKey())) {
        throw new IllegalArgumentException(String.format(
            "The field `%s` in the JSON string is not defined in the `TicketReservationResponse` properties. JSON: %s",
            entry.getKey(), jsonElement.toString()));
      }
    }

    // check to make sure all required properties/fields are present in the JSON string
    for (String requiredField : TicketReservationResponse.openapiRequiredFields) {
      if (jsonElement.getAsJsonObject().get(requiredField) == null) {
        throw new IllegalArgumentException(
            String.format("The required field `%s` is not found in the JSON string: %s",
                requiredField, jsonElement.toString()));
      }
    }
    JsonObject jsonObj = jsonElement.getAsJsonObject();
    if (!jsonObj.get("id").isJsonPrimitive()) {
      throw new IllegalArgumentException(String.format(
          "Expected the field `id` to be a primitive type in the JSON string but got `%s`",
          jsonObj.get("id").toString()));
    }
    // validate the required field `ticketPrice`
    Price.validateJsonElement(jsonObj.get("ticketPrice"));
    // validate the required field `totalPrice`
    Price.validateJsonElement(jsonObj.get("totalPrice"));
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {

    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
      if (!TicketReservationResponse.class.isAssignableFrom(type.getRawType())) {
        return null; // this class only serializes 'TicketReservationResponse' and its subtypes
      }
      final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
      final TypeAdapter<TicketReservationResponse> thisAdapter
          = gson.getDelegateAdapter(this, TypeToken.get(TicketReservationResponse.class));

      return (TypeAdapter<T>) new TypeAdapter<TicketReservationResponse>() {
        @Override
        public void write(JsonWriter out, TicketReservationResponse value) throws IOException {
          JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
          elementAdapter.write(out, obj);
        }

        @Override
        public TicketReservationResponse read(JsonReader in) throws IOException {
          JsonElement jsonElement = elementAdapter.read(in);
          validateJsonElement(jsonElement);
          return thisAdapter.fromJsonTree(jsonElement);
        }

      }.nullSafe();
    }
  }

  /**
   * Create an instance of TicketReservationResponse given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of TicketReservationResponse
   * @throws IOException if the JSON string is invalid with respect to TicketReservationResponse
   */
  public static TicketReservationResponse fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, TicketReservationResponse.class);
  }

  /**
   * Convert an instance of TicketReservationResponse to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

