CREATE TABLE event
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name              VARCHAR(255),
    venue             VARCHAR(255),
    start_date_time   TIMESTAMP WITHOUT TIME ZONE,
    base_price        DECIMAL,
    capacity          INTEGER,
    remaining_tickets INTEGER,
    CONSTRAINT pk_event PRIMARY KEY (id)
);