CREATE TABLE "order"
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    order_number   UUID,
    reservation_id BIGINT,
    created_at     date                                    NOT NULL,
    total_price    DECIMAL,
    quantity       INTEGER                                 NOT NULL,
    status         VARCHAR(255) DEFAULT 'PENDING_PAYMENT'  NOT NULL,
    CONSTRAINT pk_order PRIMARY KEY (id)
);

CREATE TABLE reservation
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    reservation_number UUID,
    event_id           BIGINT,
    reserved_at        date,
    expires_at         date,
    quantity           INTEGER                                 NOT NULL,
    single_price       DECIMAL                                 NOT NULL,
    status             VARCHAR(255) DEFAULT 'PENDING'          NOT NULL,
    CONSTRAINT pk_reservation PRIMARY KEY (id)
);

ALTER TABLE "order"
    ADD CONSTRAINT uc_order_reservation UNIQUE (reservation_id);

ALTER TABLE "order"
    ADD CONSTRAINT FK_ORDER_ON_RESERVATION FOREIGN KEY (reservation_id) REFERENCES reservation (id);

ALTER TABLE reservation
    ADD CONSTRAINT FK_RESERVATION_ON_EVENT FOREIGN KEY (event_id) REFERENCES event (id);