CREATE TABLE orders
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    order_number   UUID,
    reservation_id BIGINT,
    created_at     date                                    NOT NULL,
    total_price    DECIMAL,
    quantity       INTEGER                                 NOT NULL,
    status         VARCHAR(255) DEFAULT 'PENDING_PAYMENT'  NOT NULL,
    CONSTRAINT pk_orders PRIMARY KEY (id)
);

CREATE TABLE reservations
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    reservation_number UUID,
    event_id           BIGINT,
    reserved_at        date,
    expires_at         date,
    quantity           INTEGER                                 NOT NULL,
    single_price       DECIMAL                                 NOT NULL,
    status             VARCHAR(255) DEFAULT 'PENDING'          NOT NULL,
    CONSTRAINT pk_reservations PRIMARY KEY (id)
);

ALTER TABLE orders
    ADD CONSTRAINT uc_orders_reservations UNIQUE (reservation_id);

ALTER TABLE "order"
    ADD CONSTRAINT FK_ORDERS_ON_RESERVATIONS FOREIGN KEY (reservation_id) REFERENCES reservations (id);

ALTER TABLE reservations
    ADD CONSTRAINT FK_RESERVATIONS_ON_EVENT FOREIGN KEY (event_id) REFERENCES event (id);